In [4]:
import pandas
import os

# This query represents dataset "CVD_Analysis" for domain "person" and was generated for All of Us Registered Tier Dataset v8
dataset_54942446_person_sql = (
    """
    SELECT
        person.person_id,
        person.birth_datetime as date_of_birth,
        p_race_concept.concept_name as race,
        p_ethnicity_concept.concept_name as ethnicity,
        p_sex_at_birth_concept.concept_name as sex_at_birth 
    FROM
        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` person 
    LEFT JOIN
        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` p_race_concept 
            ON person.race_concept_id = p_race_concept.concept_id 
    LEFT JOIN
        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` p_ethnicity_concept 
            ON person.ethnicity_concept_id = p_ethnicity_concept.concept_id 
    LEFT JOIN
        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` p_sex_at_birth_concept 
            ON person.sex_at_birth_concept_id = p_sex_at_birth_concept.concept_id  
    WHERE
        person.PERSON_ID IN (SELECT
            distinct person_id  
        FROM
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` cb_search_person  
        WHERE
            cb_search_person.person_id IN (SELECT
                person_id 
            FROM
                `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` p 
            WHERE
                age_at_cdr BETWEEN 18 AND 91 
                AND NOT EXISTS (      SELECT
                    'x'      
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.death` d      
                WHERE
                    d.person_id = p.person_id ) ) 
            AND cb_search_person.person_id IN (SELECT
                person_id 
            FROM
                `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
            WHERE
                race_concept_id IN (8527, 8516, 8515) ) 
            AND cb_search_person.person_id IN (SELECT
                person_id 
            FROM
                `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
            WHERE
                sex_at_birth_concept_id IN (45878463, 45880669) ) 
            AND cb_search_person.person_id IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3038553) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (36304833) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria ) 
            AND cb_search_person.person_id IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3004249) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (21490853) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (21492239) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3028737) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria ) 
            AND cb_search_person.person_id IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3020564) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3016723) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3051825) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (40762887) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3011884, 46235076) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria ) 
            AND cb_search_person.person_id IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3033638) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3023602) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3013473) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3007070) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3011884) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3053286) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria ) 
            AND cb_search_person.person_id IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3019900) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3027114) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3009160) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria 
            UNION
            DISTINCT SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                WHERE
                    (concept_id IN (3049873) 
                    AND is_standard = 1 ) 
                    AND visit_concept_id IN (9202) ) criteria ) )"""
)

dataset_54942446_person_df = pandas.read_gbq(
    dataset_54942446_person_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook",
)

dataset_54942446_person_df.head(5)

Downloading:   0%|          | 0/60085 [00:00<?, ?rows/s]

   person_id             date_of_birth   race           ethnicity sex_at_birth
0    1965514 1963-03-10 00:00:00+00:00  Asian  Hispanic or Latino         Male
1    3090855 1982-12-05 00:00:00+00:00  Asian  Hispanic or Latino         Male
2    2811156 1983-09-01 00:00:00+00:00  Asian  Hispanic or Latino         Male
3    1689114 1997-07-04 00:00:00+00:00  Asian  Hispanic or Latino         Male
4    8470496 1985-09-14 00:00:00+00:00  Asian  Hispanic or Latino         Male

In [5]:
import pandas
import os

# This query represents dataset "CVD_Analysis" for domain "condition" and was generated for All of Us Registered Tier Dataset v8
dataset_54942446_condition_sql = (
    """
    SELECT
        c_occurrence.person_id,
        c_standard_concept.concept_name as standard_concept_name,
        c_occurrence.condition_start_datetime,
        c_occurrence.condition_end_datetime,
        c_source_concept.concept_name as source_concept_name,
        c_source_concept.concept_code as source_concept_code 
    FROM
        ( SELECT
            * 
        FROM
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.condition_occurrence` c_occurrence 
        WHERE
            (
                condition_source_concept_id IN (SELECT
                    DISTINCT c.concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria` c 
                JOIN
                    (SELECT
                        CAST(cr.id as string) AS id       
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria` cr       
                    WHERE
                        concept_id IN (1326492, 1326493, 1326588, 1326589, 1326590, 1326591, 1326600, 1326601, 1326602, 1326603, 1326604, 1326605, 1326606, 1326607, 1326608, 1326609, 1567940, 1567943, 1567944, 1567949, 1567956, 1567958, 1567959, 1567960, 1567964, 1567965, 1567966, 1567969, 1567971, 1567972, 1567975, 1568177, 1568178, 1568179, 1568180, 1569126, 1569127, 1569178, 1569179, 1569180, 1569192, 1569193, 1595597, 1595598, 35206878, 35206879, 35206881, 35206882, 35206884, 35206885, 35207684, 35207685, 35207686, 35207687, 35207688, 35207689, 35207691, 35207692, 35207693, 35207694, 35207695, 35207696, 35207697, 35207792, 35207793, 35207808, 35207809, 35207810, 35207811, 35207812, 35207813, 35207814, 35207815, 35207816, 35207817, 35207818, 35207819, 35207820, 35207821, 37200141, 37200142, 37200143, 37200144, 37200145, 37200146, 37200147, 37200148, 37200149, 37200150, 37200151, 37200152, 37200153, 37200154, 37200155, 37200156, 37200157, 37200158, 37200159, 37200160, 37200161,
 37200162, 37200163, 37200164, 37200165, 37200166, 37200167, 37200168, 37200170, 37200171, 37200172, 37200175, 37200176, 37200177, 37200180, 37200181, 37200182, 37200185, 37200186, 37200187, 37200188, 37200189, 37200190, 37200191, 37200192, 37200194, 37200195, 37200196, 37200198, 37200199, 37200200, 37200201, 37200202, 37200203, 37200204, 37200205, 37200206, 37200207, 37200208, 37200209, 37200210, 37200211, 37200212, 37200213, 37200214, 37200215, 37200216, 37200217, 37200218, 37200219, 37200220, 37200221, 37200222, 37200223, 37200224, 37200225, 37200227, 37200228, 37200229, 37200230, 37200232, 37200233, 37200234, 37200235, 37200237, 37200238, 37200239, 37200240, 37200242, 37200243, 37200244, 37200245, 37200246, 37200247, 37200248, 37200249, 37200251, 37200252, 37200253, 37200254, 37200255, 37200257, 37200258, 37200260, 37200261, 37200262, 37200263, 37200264, 37200265, 37200266, 37200268, 37200269, 37200270, 37200273, 37200274, 37200275, 37200278, 37200279, 37200280, 37200281, 37200284,
 37200291, 37200295, 37200297, 37200299, 37200301, 37200302, 37200303, 37200304, 37200305, 37200306, 37200310, 37200311, 37200496, 37200497, 37200498, 37200499, 37200500, 37200501, 37200502, 37200503, 37200504, 37200505, 37200506, 37200507, 37200508, 37200509, 37200510, 37200511, 37200512, 37200513, 44819697, 44819699, 44819700, 44819702, 44819712, 44819713, 44819714, 44820857, 44820858, 44820859, 44820860, 44820861, 44820869, 44820870, 44820874, 44823111, 44823119, 44823121, 44824237, 44824250, 44824251, 44824252, 44825428, 44825429, 44825430, 44825444, 44826635, 44826636, 44826642, 44826644, 44826645, 44827782, 44827794, 44827795, 44827796, 44827798, 44827799, 44827800, 44828972, 44828973, 44828982, 44830086, 44830088, 44830089, 44830090, 44831236, 44831237, 44831248, 44831249, 44831250, 44832372, 44832373, 44832374, 44832375, 44832376, 44832381, 44832384, 44832385, 44833561, 44833573, 44833576, 44833577, 44834718, 44834719, 44834720, 44834721, 44834723, 44834724, 44834732, 44834735,
 44834736, 44834737, 44835926, 44835927, 44835928, 44835943, 44835944, 44835946, 44835948, 44835949, 44835950, 44835951, 44837099, 44837110, 44837111, 45533017, 45533018, 45533019, 45533020, 45533021, 45533022, 45533023, 45533024, 45533085, 45533436, 45533456, 45533457, 45533462, 45533463, 45533464, 45534323, 45537958, 45537960, 45537961, 45537962, 45537963, 45538046, 45538392, 45538394, 45538395, 45538396, 45538397, 45542736, 45542737, 45542738, 45542741, 45542821, 45543182, 45543187, 45543188, 45543189, 45543190, 45547621, 45547622, 45547623, 45547624, 45547625, 45547626, 45547627, 45547632, 45547633, 45547635, 45548022, 45548026, 45548027, 45548028, 45548029, 45548030, 45552379, 45552381, 45552382, 45552383, 45552385, 45552386, 45552388, 45552453, 45552454, 45552801, 45552802, 45552803, 45552804, 45552805, 45552806, 45557110, 45557111, 45557112, 45557113, 45557116, 45557536, 45557548, 45557549, 45557551, 45557552, 45557553, 45557554, 45557555, 45561947, 45561948, 45561949, 45561953,
 45561954, 45561955, 45561956, 45561957, 45562025, 45562340, 45562355, 45562362, 45562363, 45562364, 45562365, 45562367, 45566729, 45566731, 45566733, 45566734, 45566735, 45566736, 45566737, 45566810, 45567180, 45567181, 45567187, 45567188, 45567189, 45568007, 45571654, 45571658, 45571659, 45571661, 45571662, 45571741, 45571742, 45571743, 45572079, 45572080, 45572097, 45572098, 45572099, 45576437, 45576438, 45576439, 45576440, 45576443, 45576446, 45576447, 45576448, 45576521, 45576865, 45576878, 45576884, 45576885, 45576886, 45576887, 45576888, 45576889, 45577675, 45581349, 45581350, 45581352, 45581353, 45581354, 45581355, 45581358, 45581359, 45581435, 45581781, 45581782, 45581783, 45581784, 45586138, 45586139, 45586140, 45586142, 45586143, 45586144, 45586145, 45586219, 45586220, 45586587, 45586588, 45586593, 45586594, 45586595, 45586596, 45586597, 45591026, 45591027, 45591029, 45591030, 45591031, 45591033, 45591034, 45591115, 45591116, 45591469, 45591474, 45591476, 45595793, 45595794,
 45595795, 45595797, 45595798, 45595799, 45595802, 45595803, 45595804, 45595805, 45595884, 45595885, 45596194, 45596212, 45596213, 45596214, 45596215, 45600636, 45600637, 45600638, 45600639, 45600640, 45600641, 45600642, 45600644, 45600719, 45600720, 45601038, 45601041, 45601042, 45601043, 45601044, 45601045, 45601046, 45601047, 45605397, 45605398, 45605401, 45605402, 45605403, 45605404, 45605405, 45605476, 45605779, 45605781, 45605805, 45605806, 45605807, 45605809, 45606676)       
                        AND full_text LIKE '%_rank1]%'      ) a 
                        ON (c.path LIKE CONCAT('%.', a.id, '.%') 
                        OR c.path LIKE CONCAT('%.', a.id) 
                        OR c.path LIKE CONCAT(a.id, '.%') 
                        OR c.path = a.id) 
                WHERE
                    is_standard = 0 
                    AND is_selectable = 1)
            )  
            AND (
                c_occurrence.PERSON_ID IN (SELECT
                    distinct person_id  
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` cb_search_person  
                WHERE
                    cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` p 
                    WHERE
                        age_at_cdr BETWEEN 18 AND 91 
                        AND NOT EXISTS (      SELECT
                            'x'      
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.death` d      
                        WHERE
                            d.person_id = p.person_id ) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        race_concept_id IN (8527, 8516, 8515) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        sex_at_birth_concept_id IN (45878463, 45880669) ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3038553) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (36304833) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3004249) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21490853) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21492239) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3028737) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3020564) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3016723) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3051825) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (40762887) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884, 46235076) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3033638) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3023602) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3013473) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3007070) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3053286) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3019900) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3027114) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3009160) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3049873) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) )
                )
            ) c_occurrence 
        LEFT JOIN
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` c_standard_concept 
                ON c_occurrence.condition_concept_id = c_standard_concept.concept_id 
        LEFT JOIN
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` c_source_concept 
                ON c_occurrence.condition_source_concept_id = c_source_concept.concept_id"""
)

dataset_54942446_condition_df = pandas.read_gbq(
    dataset_54942446_condition_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook",
)

dataset_54942446_condition_df.head(5)

Downloading:   0%|          | 0/1489577 [00:00<?, ?rows/s]

,person_id,standard_concept_name,condition_start_datetime,condition_end_datetime,source_concept_name,source_concept_code
0,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-07-15 00:00:00+00:00,2021-07-15 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
1,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-10-06 00:00:00+00:00,2021-10-06 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
2,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-07-15 00:00:00+00:00,2021-07-15 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
3,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-10-06 00:00:00+00:00,2021-10-06 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
4,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-07-15 00:00:00+00:00,2021-07-15 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1

In [6]:
import pandas
import os

# This query represents dataset "CVD_Analysis" for domain "drug" and was generated for All of Us Registered Tier Dataset v8
dataset_54942446_drug_sql = (
    """
    SELECT
        d_exposure.person_id,
        d_standard_concept.vocabulary_id as standard_vocabulary,
        d_exposure.drug_exposure_start_datetime,
        d_exposure.drug_exposure_end_datetime 
    FROM
        ( SELECT
            * 
        FROM
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.drug_exposure` d_exposure 
        WHERE
            (
                drug_concept_id IN (SELECT
                    DISTINCT ca.descendant_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria_ancestor` ca 
                JOIN
                    (SELECT
                        DISTINCT c.concept_id       
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria` c       
                    JOIN
                        (SELECT
                            CAST(cr.id as string) AS id             
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria` cr             
                        WHERE
                            concept_id IN (21600381)             
                            AND full_text LIKE '%_rank1]%'       ) a 
                            ON (c.path LIKE CONCAT('%.', a.id, '.%') 
                            OR c.path LIKE CONCAT('%.', a.id) 
                            OR c.path LIKE CONCAT(a.id, '.%') 
                            OR c.path = a.id) 
                    WHERE
                        is_standard = 1 
                        AND is_selectable = 1) b 
                        ON (ca.ancestor_id = b.concept_id)))  
                    AND (d_exposure.PERSON_ID IN (SELECT
                        distinct person_id  
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` cb_search_person  
                WHERE
                    cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` p 
                    WHERE
                        age_at_cdr BETWEEN 18 AND 91 
                        AND NOT EXISTS (      SELECT
                            'x'      
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.death` d      
                        WHERE
                            d.person_id = p.person_id ) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        race_concept_id IN (8527, 8516, 8515) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        sex_at_birth_concept_id IN (45878463, 45880669) ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3038553) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (36304833) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3004249) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21490853) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21492239) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3028737) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3020564) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3016723) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3051825) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (40762887) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884, 46235076) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3033638) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3023602) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3013473) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3007070) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3053286) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3019900) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3027114) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3009160) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3049873) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) )
                )
            ) d_exposure 
        LEFT JOIN
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` d_standard_concept 
                ON d_exposure.drug_concept_id = d_standard_concept.concept_id"""
)

dataset_54942446_drug_df = pandas.read_gbq(
    dataset_54942446_drug_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook",
)

dataset_54942446_drug_df.head(5)

Downloading:   0%|          | 0/172366 [00:00<?, ?rows/s]

,person_id,standard_vocabulary,drug_exposure_start_datetime,drug_exposure_end_datetime
0,3018640,RxNorm,2021-11-16 09:00:00+00:00,2021-11-26 01:24:00+00:00
1,1453761,RxNorm,2019-05-12 05:00:00+00:00,NaT
2,1453761,RxNorm,2022-09-29 05:00:00+00:00,NaT
3,1453761,RxNorm,2020-07-23 05:00:00+00:00,NaT
4,1453761,RxNorm,2019-02-20 05:00:00+00:00,NaT

In [7]:
import pandas
import os

# This query represents dataset "CVD_Analysis" for domain "measurement" and was generated for All of Us Registered Tier Dataset v8
dataset_54942446_measurement_sql = (
    """
    SELECT
        measurement.person_id,
        measurement.measurement_datetime,
        measurement.value_as_number,
        m_source_concept.concept_name as source_concept_name,
        m_source_concept.concept_code as source_concept_code 
    FROM
        ( SELECT
            * 
        FROM
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.measurement` measurement 
        WHERE
            (
                measurement_concept_id IN (SELECT
                    DISTINCT c.concept_id 
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria` c 
                JOIN
                    (SELECT
                        CAST(cr.id as string) AS id       
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_criteria` cr       
                    WHERE
                        concept_id IN (21490853, 21492239, 3004249, 3007070, 3009160, 3011884, 3013473, 3016723, 3019900, 3020564, 3023602, 3027114, 3028737, 3033638, 3038553, 3049873, 3051825, 3053286, 36304833, 40762887, 46235076)       
                        AND full_text LIKE '%_rank1]%'      ) a 
                        ON (c.path LIKE CONCAT('%.', a.id, '.%') 
                        OR c.path LIKE CONCAT('%.', a.id) 
                        OR c.path LIKE CONCAT(a.id, '.%') 
                        OR c.path = a.id) 
                WHERE
                    is_standard = 1 
                    AND is_selectable = 1)
            )  
            AND (
                measurement.PERSON_ID IN (SELECT
                    distinct person_id  
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` cb_search_person  
                WHERE
                    cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` p 
                    WHERE
                        age_at_cdr BETWEEN 18 AND 91 
                        AND NOT EXISTS (      SELECT
                            'x'      
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.death` d      
                        WHERE
                            d.person_id = p.person_id ) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        race_concept_id IN (8527, 8516, 8515) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        sex_at_birth_concept_id IN (45878463, 45880669) ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3038553) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (36304833) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3004249) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21490853) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21492239) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3028737) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3020564) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3016723) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3051825) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (40762887) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884, 46235076) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3033638) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3023602) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3013473) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3007070) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3053286) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3019900) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3027114) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3009160) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3049873) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) )
                )
            ) measurement 
        LEFT JOIN
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` m_source_concept 
                ON measurement.measurement_source_concept_id = m_source_concept.concept_id"""
)

dataset_54942446_measurement_df = pandas.read_gbq(
    dataset_54942446_measurement_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook",
)

dataset_54942446_measurement_df.head(5)

Downloading:   0%|          | 0/10613608 [00:00<?, ?rows/s]

,person_id,measurement_datetime,value_as_number,source_concept_name,source_concept_code
0,1699151,2016-07-19 05:00:00+00:00,157.0,None,None
1,3068304,2019-01-03 22:00:00+00:00,158.0,None,None
2,3207634,2018-04-17 05:03:00+00:00,94.0,None,None
3,2696082,2007-07-28 12:50:00.071000+00:00,222.0,None,None
4,1877149,2023-04-09 17:14:15+00:00,29.6,None,None

In [8]:
import pandas
import os

# This query represents dataset "CVD_Analysis" for domain "observation" and was generated for All of Us Registered Tier Dataset v8
dataset_54942446_observation_sql = (
    """
    SELECT
        observation.person_id,
        observation.observation_datetime,
        observation.observation_source_value,
        o_source_concept.concept_name as source_concept_name,
        o_source_concept.concept_code as source_concept_code 
    FROM
        ( SELECT
            * 
        FROM
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.observation` observation 
        WHERE
            (
                observation_source_concept_id IN (45534323, 45556846, 45568007, 45576521, 45577675, 45606676, 45606677)
            )  
            AND (
                observation.PERSON_ID IN (SELECT
                    distinct person_id  
                FROM
                    `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` cb_search_person  
                WHERE
                    cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_person` p 
                    WHERE
                        age_at_cdr BETWEEN 18 AND 91 
                        AND NOT EXISTS (      SELECT
                            'x'      
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.death` d      
                        WHERE
                            d.person_id = p.person_id ) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        race_concept_id IN (8527, 8516, 8515) ) 
                    AND cb_search_person.person_id IN (SELECT
                        person_id 
                    FROM
                        `"""
    + os.environ["WORKSPACE_CDR"]
    + """.person` p 
                    WHERE
                        sex_at_birth_concept_id IN (45878463, 45880669) ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3038553) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (36304833) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3004249) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21490853) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (21492239) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3028737) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3020564) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3016723) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3051825) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (40762887) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884, 46235076) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3033638) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3023602) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3013473) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3007070) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3011884) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3053286) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) 
                    AND cb_search_person.person_id IN (SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3019900) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3027114) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3009160) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria 
                    UNION
                    DISTINCT SELECT
                        criteria.person_id 
                    FROM
                        (SELECT
                            DISTINCT person_id, entry_date, concept_id 
                        FROM
                            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.cb_search_all_events` 
                        WHERE
                            (concept_id IN (3049873) 
                            AND is_standard = 1 ) 
                            AND visit_concept_id IN (9202) ) criteria ) )
                )
            ) observation 
        LEFT JOIN
            `"""
    + os.environ["WORKSPACE_CDR"]
    + """.concept` o_source_concept 
                ON observation.observation_source_concept_id = o_source_concept.concept_id"""
)

dataset_54942446_observation_df = pandas.read_gbq(
    dataset_54942446_observation_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook",
)

dataset_54942446_observation_df.head(5)

Downloading:   0%|          | 0/20 [00:00<?, ?rows/s]

,person_id,observation_datetime,observation_source_value,source_concept_name,source_concept_code
0,1297580,2020-07-30 22:57:00+00:00,O99.335,Smoking (tobacco) complicating the puerperium,O99.335
1,1254842,2021-10-28 00:00:00+00:00,O99.332,"Smoking (tobacco) complicating pregnancy, seco...",O99.332
2,1297580,2020-08-08 00:28:00+00:00,O99.335,Smoking (tobacco) complicating the puerperium,O99.335
3,2104886,2018-04-17 00:00:00+00:00,O99.331,"Smoking (tobacco) complicating pregnancy, firs...",O99.331
4,2104886,2018-04-17 00:00:00+00:00,O99.331,"Smoking (tobacco) complicating pregnancy, firs...",O99.331

In [9]:
# Labs
dat_lab = dataset_54942446_measurement_df.copy()

In [10]:
# Split Data
# drop na
dat_lab = dat_lab.dropna()

import pandas as pd

# ICD codes for lab mapping
scre_codes = {
    "103616-9",
    "14682-9",
    "2160-0",
    "35203-9",
    "38483-4",
    "44784-7",
    "59826-8",
    "77140-2",
}
sbp_codes = {"75997-7", "76215-3", "76534-7", "8479-8", "8480-6", "8508-4"}
bmi_codes = {"39156-5", "41909-3", "89270-3"}
hdlc_codes = {
    "12771-2",
    "12772-0",
    "14646-4",
    "18263-4",
    "2085-9",
    "27340-9",
    "35197-3",
    "49130-8",
}
tc_codes = {"14647-2", "2093-3", "2565-0", "35200-5", "9342-7", "48620-9"}

# filter original df
dat_scre = dat_lab[dat_lab["source_concept_code"].astype(str).isin(scre_codes)]
dat_sbp = dat_lab[dat_lab["source_concept_code"].astype(str).isin(sbp_codes)]
dat_bmi = dat_lab[dat_lab["source_concept_code"].astype(str).isin(bmi_codes)]
dat_hdlc = dat_lab[dat_lab["source_concept_code"].astype(str).isin(hdlc_codes)]
dat_tc = dat_lab[dat_lab["source_concept_code"].astype(str).isin(tc_codes)]

# shape
print(f"dat_scre: {dat_scre.shape}")
print(f"dat_sbp: {dat_sbp.shape}")
print(f"dat_bmi: {dat_bmi.shape}")
print(f"dat_hdlc: {dat_hdlc.shape}")
print(f"dat_tc: {dat_tc.shape}")

dat_scre: (1289063, 5)
dat_sbp: (3782545, 5)
dat_bmi: (1507594, 5)
dat_hdlc: (363619, 5)
dat_tc: (377821, 5)

### Find Index Date

* Logic: The most recent date between earliest pair of sbp and scre record within 1 year timeframe from each other for each patient
* Purpose: Mark the start of follow up, make sure all lab records we will use for prediction is before this date and CVD event after this date to ensure fairness in risk prediction

In [11]:
import pandas as pd
import numpy as np

# Fix SettingWithCopyWarning by creating explicit copies before modification
# or by using .loc for assignment operations

# Make explicit copies to avoid SettingWithCopyWarning
dat_sbp_copy = dat_sbp.copy()
dat_scre_copy = dat_scre.copy()

# Convert to datetime
dat_sbp_copy.loc[:, "measurement_datetime"] = pd.to_datetime(
    dat_sbp_copy["measurement_datetime"]
)
dat_scre_copy.loc[:, "measurement_datetime"] = pd.to_datetime(
    dat_scre_copy["measurement_datetime"]
)

# Select, drop duplicates, and rename in a single chain
dat_sbp = (
    dat_sbp_copy[["person_id", "measurement_datetime", "value_as_number"]]
    .drop_duplicates()
    .rename(
        columns={"measurement_datetime": "sbp_date", "value_as_number": "sbp_result"}
    )
)

dat_scre = (
    dat_scre_copy[["person_id", "measurement_datetime", "value_as_number"]]
    .drop_duplicates()
    .rename(
        columns={"measurement_datetime": "scre_date", "value_as_number": "scre_result"}
    )
)

# Create year timeframe - use loc for assignment to avoid warnings
dat_sbp.loc[:, "year_range"] = pd.Timedelta(days=365)

# Find common patient IDs - use faster numpy-based intersection
sbp_ids = dat_sbp["person_id"].values
scre_ids = dat_scre["person_id"].values
pat_both = np.intersect1d(sbp_ids, scre_ids)

# Filter data using faster isin with numpy array
dat_sbp_filtered = dat_sbp[dat_sbp["person_id"].isin(pat_both)]
dat_scre_filtered = dat_scre[dat_scre["person_id"].isin(pat_both)]

# Create indices for faster merges
dat_sbp_filtered = dat_sbp_filtered.set_index("person_id").sort_index()
dat_scre_filtered = dat_scre_filtered.set_index("person_id").sort_index()


# Helper function for chunking
def process_in_chunks(ids, chunk_size=1000):
    num_chunks = (len(ids) + chunk_size - 1) // chunk_size
    for i in range(0, len(ids), chunk_size):
        chunk_ids = ids[i : i + chunk_size]
        print(f"Processing chunk {i//chunk_size + 1}/{num_chunks}")
        yield chunk_ids


# Process data in chunks
results = []
for chunk_ids in process_in_chunks(pat_both, chunk_size=1000):
    # Get data for current chunk
    df_sbp_tmp = dat_sbp_filtered.loc[chunk_ids].reset_index()
    df_scre_tmp = dat_scre_filtered.loc[chunk_ids].reset_index()

    # Merge data with inner join
    tmp = pd.merge(df_scre_tmp, df_sbp_tmp, on="person_id", how="inner")

    # Filter by date range
    mask = (tmp["scre_date"] >= (tmp["sbp_date"] - tmp["year_range"])) & (
        tmp["scre_date"] <= (tmp["sbp_date"] + tmp["year_range"])
    )
    tmp = tmp[mask]

    if tmp.empty:
        continue

    # Calculate time differences and minimize dates - use loc for new columns
    tmp.loc[:, "col_diff"] = (tmp["scre_date"] - tmp["sbp_date"]).abs()

    # Use numpy's minimum function for better performance
    tmp.loc[:, "col_min"] = np.minimum(
        tmp["scre_date"].values.astype("datetime64[ns]"),
        tmp["sbp_date"].values.astype("datetime64[ns]"),
    )

    # Sort and take first record for each patient
    tmp = tmp.sort_values(["person_id", "col_min", "col_diff"])
    tmp_sel = tmp.groupby("person_id", as_index=False).first()

    # Calculate index date using numpy for better performance
    tmp_sel.loc[:, "INDEX_DATE"] = np.maximum(
        tmp_sel["scre_date"].values.astype("datetime64[ns]"),
        tmp_sel["sbp_date"].values.astype("datetime64[ns]"),
    )

    # Select needed columns
    results.append(tmp_sel[["person_id", "INDEX_DATE", "scre_result", "sbp_result"]])

# Combine results if any exist
dat_index = pd.concat(results, ignore_index=True)
print(f"Number of patients with index date: {len(dat_index)}")
display(dat_index.head())

Processing chunk 1/36
Processing chunk 2/36
Processing chunk 3/36
Processing chunk 4/36
Processing chunk 5/36
Processing chunk 6/36
Processing chunk 7/36
Processing chunk 8/36
Processing chunk 9/36
Processing chunk 10/36
Processing chunk 11/36
Processing chunk 12/36
Processing chunk 13/36
Processing chunk 14/36
Processing chunk 15/36
Processing chunk 16/36
Processing chunk 17/36
Processing chunk 18/36
Processing chunk 19/36
Processing chunk 20/36
Processing chunk 21/36
Processing chunk 22/36
Processing chunk 23/36
Processing chunk 24/36
Processing chunk 25/36
Processing chunk 26/36
Processing chunk 27/36
Processing chunk 28/36
Processing chunk 29/36
Processing chunk 30/36
Processing chunk 31/36
Processing chunk 32/36
Processing chunk 33/36
Processing chunk 34/36
Processing chunk 35/36
Processing chunk 36/36
Number of patients with index date: 35460

   person_id          INDEX_DATE  scre_result  sbp_result
0    1000127 2005-11-08 19:09:00         0.70       114.0
1    1000164 2009-06-17 00:00:00         0.90       108.0
2    1000174 2019-03-23 16:01:00         0.65       132.0
3    1000196 2015-11-16 12:10:00         0.88       127.0
4    1000207 2009-05-05 05:00:00         0.90       132.0

### Merge All Labs

In [12]:
def merge_all_measurements(index_df, measurement_dfs, lookback_years=3):
    # copy
    result_df = index_df.copy()

    # convert to datetime
    result_df["INDEX_DATE"] = pd.to_datetime(result_df["INDEX_DATE"]).dt.tz_localize(
        None
    )
    print("Preprocessing index dataframe...")

    # lookback window
    lookback_limits = result_df["INDEX_DATE"] - pd.DateOffset(years=lookback_years)

    # track progress
    total_measurements = len(measurement_dfs)
    measurement_count = 0

    # process each measurement type
    for measurement_type, measurement_df in measurement_dfs.items():
        measurement_count += 1
        print(
            f"\nProcessing {measurement_type} ({measurement_count}/{total_measurements})..."
        )

        # convert to datetime
        meas_df = measurement_df.copy()
        meas_df["measurement_datetime"] = pd.to_datetime(
            meas_df["measurement_datetime"]
        ).dt.tz_localize(None)

        # init result columns
        result_df[f"{measurement_type}_value"] = np.nan
        result_df[f"{measurement_type}_date"] = pd.NaT
        result_df[f"{measurement_type}_days_diff"] = np.nan

        # store
        measurement_results = []

        # grouping
        print(f"  Grouping {measurement_type} measurements by person_id...")
        grouped_measurements = dict(list(meas_df.groupby("person_id")))

        # progress update
        total_rows = len(result_df)
        update_interval = max(1, total_rows // 20)

        print(f"  Processing {total_rows} people for {measurement_type} measurements:")

        for idx, (i, row) in enumerate(result_df.iterrows()):
            # show progress
            if idx % update_interval == 0 or idx == total_rows - 1:
                progress_pct = min(100, round((idx + 1) / total_rows * 100))
                print(f"  Progress: {progress_pct}% ({idx + 1}/{total_rows})", end="\r")

            person_id = row["person_id"]
            index_date = row["INDEX_DATE"]
            lookback_limit = lookback_limits.loc[i]

            # skip processing if person has no measurements
            if person_id not in grouped_measurements:
                measurement_results.append((np.nan, pd.NaT, np.nan))
                continue

            # get all measurements for this person
            person_meas = grouped_measurements[person_id]

            # filter by date using vectorized operations
            valid_meas = person_meas[
                (person_meas["measurement_datetime"] <= index_date)
                & (person_meas["measurement_datetime"] >= lookback_limit)
            ]

            if valid_meas.empty:
                measurement_results.append((np.nan, pd.NaT, np.nan))
                continue

            # calculate days difference using vectorized operations
            valid_meas = valid_meas.copy()
            valid_meas["days_diff"] = (
                index_date - valid_meas["measurement_datetime"]
            ).dt.days

            # find closest measurement
            closest_idx = valid_meas["days_diff"].idxmin()
            closest_meas = valid_meas.loc[closest_idx]

            measurement_results.append(
                (
                    closest_meas["value_as_number"],
                    closest_meas["measurement_datetime"],
                    closest_meas["days_diff"],
                )
            )

        print("\n  Updating result dataframe...")
        # nulk update the result dataframe
        result_df[
            [
                f"{measurement_type}_value",
                f"{measurement_type}_date",
                f"{measurement_type}_days_diff",
            ]
        ] = measurement_results

        # show completion for this measurement type
        print(f"  Completed processing {measurement_type} measurements")

    print("\nAll measurements processed successfully!")
    return result_df


# using the optimized function
measurement_dfs = {"bmi": dat_bmi, "tc": dat_tc, "hdlc": dat_hdlc}

final_result = merge_all_measurements(dat_index, measurement_dfs)

# drop helper columns
columns_to_drop = [
    "bmi_date",
    "bmi_days_diff",
    "tc_date",
    "tc_days_diff",
    "hdlc_date",
    "hdlc_days_diff",
]
final_result = final_result.drop(columns=columns_to_drop)

# drop na
final_result = final_result.dropna()

# 14119 patients
print(f"Final dataframe shape: {final_result.shape}")
final_result.head()

Preprocessing index dataframe...

Processing bmi (1/3)...
  Grouping bmi measurements by person_id...
  Processing 35460 people for bmi measurements:
  Progress: 100% (35460/35460)
  Updating result dataframe...
  Completed processing bmi measurements

Processing tc (2/3)...
  Grouping tc measurements by person_id...
  Processing 35460 people for tc measurements:
  Progress: 100% (35460/35460)
  Updating result dataframe...
  Completed processing tc measurements

Processing hdlc (3/3)...
  Grouping hdlc measurements by person_id...
  Processing 35460 people for hdlc measurements:
  Progress: 100% (35460/35460)
  Updating result dataframe...
  Completed processing hdlc measurements

All measurements processed successfully!
Final dataframe shape: (14023, 7)

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value
2,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0
3,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0
4,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0
8,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0
12,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0

### Merge Smoker Data

In [23]:
# make copy
final_result = final_result.copy()

# convert to datetime
dataset_54942446_observation_df["observation_datetime"] = pd.to_datetime(
    dataset_54942446_observation_df["observation_datetime"]
).dt.tz_localize(None)
final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# map person id to all smoker record dates
smoker_dict = {}
for person_id, group in dataset_54942446_observation_df.groupby("person_id"):
    smoker_dict[person_id] = group["observation_datetime"].tolist()


# helper function
def has_smoking_record(row):
    person_id = row["person_id"]
    index_date = row["INDEX_DATE"]

    # if not in dict, then 0
    if person_id not in smoker_dict:
        return 0

    # get all dates
    obs_dates = smoker_dict[person_id]

    # check if any date is within 3 years (1095 days)
    for date in obs_dates:
        if abs((date - index_date).days) <= 1095:
            return 1

    return 0


# apply function
final_result.loc[:, "smoker"] = final_result.apply(has_smoking_record, axis=1)

In [24]:
final_result.head()

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value,smoker
2,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0,0
3,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0,0
4,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0,0
8,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0,0
12,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0,0

### Merge Antihypertensive Medication Data

In [26]:
# Make a copy of final_result to avoid modifying the original data
final_result = final_result.copy()

# Convert date columns to datetime format and remove timezone information
dataset_54942446_drug_df.loc[:, "drug_exposure_start_datetime"] = pd.to_datetime(
    dataset_54942446_drug_df["drug_exposure_start_datetime"]
).dt.tz_localize(None)

dataset_54942446_drug_df.loc[:, "drug_exposure_end_datetime"] = pd.to_datetime(
    dataset_54942446_drug_df["drug_exposure_end_datetime"]
).dt.tz_localize(None)

final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# Create a dictionary mapping person_id to all drug exposure start and end dates
drug_exposure_dict = {}
for person_id, group in dataset_54942446_drug_df.groupby("person_id"):
    drug_exposure_dict[person_id] = list(
        zip(group["drug_exposure_start_datetime"], group["drug_exposure_end_datetime"])
    )


# Helper function to check if a person has drug exposure within the 3-year lookback window
def has_antihypertensive_record(row):
    person_id = row["person_id"]
    index_date = row["INDEX_DATE"]

    # If person_id not in the dictionary, return 0
    if person_id not in drug_exposure_dict:
        return 0

    # Get all drug exposure periods
    exposure_periods = drug_exposure_dict[person_id]

    # Check if any exposure period falls within the 3-year (1095 days) lookback window
    for start_date, end_date in exposure_periods:
        if (index_date - pd.Timedelta(days=1095) <= start_date <= index_date) or (
            index_date - pd.Timedelta(days=1095) <= end_date <= index_date
        ):
            return 1

    return 0


# Apply function to create the 'antihtn' column
final_result.loc[:, "antihtn"] = final_result.apply(has_antihypertensive_record, axis=1)

# Display the updated DataFrame
final_result.head()

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value,smoker,antihtn
2,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0,0,0
3,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0,0,0
4,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0,0,0
8,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0,0,0
12,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0,0,0

### Merge Diabetes Data

In [27]:
# convert data type
dataset_54942446_condition_df["source_concept_code"] = dataset_54942446_condition_df[
    "source_concept_code"
].astype(str)

# filter diabetes data base on ICD codes
dat_db = dataset_54942446_condition_df[
    dataset_54942446_condition_df["source_concept_code"].str.startswith(
        ("E10", "E11", "E13")
    )
]

dat_db.head()

,person_id,standard_concept_name,condition_start_datetime,condition_end_datetime,source_concept_name,source_concept_code
0,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-07-15 00:00:00+00:00,2021-07-15 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
1,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-10-06 00:00:00+00:00,2021-10-06 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
2,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-07-15 00:00:00+00:00,2021-07-15 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
3,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-10-06 00:00:00+00:00,2021-10-06 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1
4,1515353,Disorder of eye due to type 1 diabetes mellitus,2021-07-15 00:00:00+00:00,2021-07-15 00:00:00+00:00,Type 1 diabetes mellitus with diabetic macular...,E10.37X1

In [29]:
# convert to datetime
dat_db.loc[:, "condition_start_datetime"] = pd.to_datetime(
    dat_db["condition_start_datetime"]
).dt.tz_localize(None)

final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# map person id to all db record dates
db_dict = {}
for person_id, group in dat_db.groupby("person_id"):
    db_dict[person_id] = group["condition_start_datetime"].tolist()


# helper function
def has_db_record(row):
    person_id = row["person_id"]
    index_date = row["INDEX_DATE"]

    # if not in dict, then 0
    if person_id not in db_dict:
        return 0

    # get all dates
    obs_dates = db_dict[person_id]

    # check if any date is within 3 years (1095 days)
    for date in obs_dates:
        if abs((date - index_date).days) <= 1095:
            return 1

    return 0


# apply function
final_result.loc[:, "diabetes"] = final_result.apply(has_db_record, axis=1)
final_result.head()

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value,smoker,antihtn,diabetes
2,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0,0,0,0
3,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0,0,0,0
4,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0,0,0,0
8,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0,0,0,0
12,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0,0,0,1

### Merge Events Data

In [31]:
# filter by ICD codes
dat_mi = dataset_54942446_condition_df[
    dataset_54942446_condition_df["source_concept_code"].str.startswith(
        ("410", "I21", "I22", "I23")
    )
]

dat_stroke = dataset_54942446_condition_df[
    dataset_54942446_condition_df["source_concept_code"].str.startswith(
        ("431", "432", "433", "434", "I61", "I62", "I63")
    )
]

dat_hf = dataset_54942446_condition_df[
    dataset_54942446_condition_df["source_concept_code"].str.startswith(("428", "I50"))
]

#### Myocardial Infarction

In [33]:
# Myocardial Infarction
# convert datetime
dat_mi.loc[:, "condition_start_datetime"] = pd.to_datetime(
    dat_mi["condition_start_datetime"]
).dt.tz_localize(None)
final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# mapping dict
mi_dict = {}
for person_id, group in dat_mi.groupby("person_id"):
    mi_dict[person_id] = group["condition_start_datetime"].tolist()


# helper function
def assign_mi(row):
    person_id = row["person_id"]
    index_date = row["INDEX_DATE"]

    # if person not in mi_dict, assign 0
    if person_id not in mi_dict:
        return 0

    # get all dates
    condition_dates = mi_dict[person_id]

    # if event before INDEX_DATE, mark for removal
    if any(date < index_date for date in condition_dates):
        return "REMOVE"

    # otherwise, assign 1
    return 1


# apply function to create mi column
final_result.loc[:, "mi"] = final_result.apply(assign_mi, axis=1)

# remove rows where 'mi' is 'REMOVE'
final_result = final_result[final_result["mi"] != "REMOVE"]

# convert column back to integers
final_result.loc[:, "mi"] = final_result["mi"].astype(int)

final_result.head()

#### Stroke

In [ ]:
# convert datetime
dat_stroke.loc[:, "condition_start_datetime"] = pd.to_datetime(
    dat_stroke["condition_start_datetime"]
).dt.tz_localize(None)
final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# mapping dict
stroke_dict = {}
for person_id, group in dat_stroke.groupby("person_id"):
    stroke_dict[person_id] = group["condition_start_datetime"].tolist()


# helper function
def assign_stroke(row):
    person_id = row["person_id"]
    index_date = row["INDEX_DATE"]

    # if person not in stroke_dict, assign 0
    if person_id not in stroke_dict:
        return 0

    # get all dates
    condition_dates = stroke_dict[person_id]

    # if event before INDEX_DATE, mark for removal
    if any(date < index_date for date in condition_dates):
        return "REMOVE"

    # otherwise, assign 1
    return 1


# apply function to create stroke column
final_result.loc[:, "stroke"] = final_result.apply(assign_stroke, axis=1)

# remove rows where 'stroke' is 'REMOVE'
final_result = final_result[final_result["stroke"] != "REMOVE"]

# convert column back to integers
final_result.loc[:, "stroke"] = final_result["stroke"].astype(int)
final_result.head()

#### Heart Failure

In [37]:
# convert datetime
dat_hf.loc[:, "condition_start_datetime"] = pd.to_datetime(
    dat_hf["condition_start_datetime"]
).dt.tz_localize(None)
final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# mapping dict
hf_dict = {}
for person_id, group in dat_hf.groupby("person_id"):
    hf_dict[person_id] = group["condition_start_datetime"].tolist()


# helper function
def assign_hf(row):
    person_id = row["person_id"]
    index_date = row["INDEX_DATE"]

    # if person not in hf_dict, assign 0
    if person_id not in hf_dict:
        return 0

    # get all dates
    condition_dates = hf_dict[person_id]

    # if event before INDEX_DATE, mark for removal
    if any(date < index_date for date in condition_dates):
        return "REMOVE"

    # otherwise, assign 1
    return 1


# apply function to create hf column
final_result.loc[:, "hf"] = final_result.apply(assign_hf, axis=1)

# remove rows where 'hf' is 'REMOVE'
final_result = final_result[final_result["hf"] != "REMOVE"]

# convert column back to integers
final_result.loc[:, "hf"] = final_result["hf"].astype(int)

In [38]:
final_result.head()

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value,smoker,antihtn,diabetes,mi,stroke,hf
2,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0,0,0,0,0,0,0
3,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0,0,0,0,0,0,0
4,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0,0,0,0,0,0,0
8,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0,0,0,0,0,0,0
12,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0,0,0,1,1,0,1

#### CVD and ASCVD

In [39]:
# create 'cvd' column: assign 1 if any of 'mi', 'stroke', or 'hf' is 1, otherwise 0
final_result.loc[:, "cvd"] = (
    (final_result["mi"] == 1)
    | (final_result["stroke"] == 1)
    | (final_result["hf"] == 1)
).astype(int)

# create 'ascvd' column: assign 1 if any of 'mi' or 'stroke' is 1, otherwise 0
final_result.loc[:, "ascvd"] = (
    (final_result["mi"] == 1) | (final_result["stroke"] == 1)
).astype(int)
final_result.head()

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value,smoker,antihtn,diabetes,mi,stroke,hf,cvd,ascvd
2,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0,0,0,0,0,0,0,0,0
3,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0,0,0,0,0,0,0,0,0
4,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0,0,0,0,0,0,0,0,0
8,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0,0,0,0,0,0,0,0,0
12,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0,0,0,1,1,0,1,1,1

### Demographic Data

In [40]:
# convert to datetime
dataset_54942446_person_df.loc[:, "date_of_birth"] = pd.to_datetime(
    dataset_54942446_person_df["date_of_birth"]
).dt.tz_localize(None)
final_result.loc[:, "INDEX_DATE"] = pd.to_datetime(
    final_result["INDEX_DATE"]
).dt.tz_localize(None)

# inner join
final_result = final_result.merge(
    dataset_54942446_person_df, on="person_id", how="inner"
)

# get age: difference in years between INDEX_DATE and date_of_birth
final_result.loc[:, "age"] = (
    final_result["INDEX_DATE"] - final_result["date_of_birth"]
).dt.days // 365

final_result.head()

,person_id,INDEX_DATE,scre_result,sbp_result,bmi_value,tc_value,hdlc_value,smoker,antihtn,diabetes,mi,stroke,hf,cvd,ascvd,date_of_birth,race,ethnicity,sex_at_birth,age
0,1000174,2019-03-23 16:01:00,0.65,132.0,44.52,161.0,38.0,0,0,0,0,0,0,0,0,1980-11-15,White,Not Hispanic or Latino,Female,38
1,1000196,2015-11-16 12:10:00,0.88,127.0,29.5,211.0,47.0,0,0,0,0,0,0,0,0,1957-05-03,White,Not Hispanic or Latino,Male,58
2,1000207,2009-05-05 05:00:00,0.90,132.0,26.64,198.0,52.0,0,0,0,0,0,0,0,0,1942-07-31,White,Not Hispanic or Latino,Female,66
3,1000536,2020-04-03 22:44:00,0.70,144.0,22.6,185.0,41.0,0,0,0,0,0,0,0,0,1992-02-27,White,Not Hispanic or Latino,Female,28
4,1000678,2014-01-09 12:17:00,1.05,128.0,37.540001,237.0,51.0,0,0,1,1,0,1,1,1,1952-08-28,Black or African American,Not Hispanic or Latino,Female,61

### Save Data

In [44]:
# rename columns
final_result = final_result.rename(
    columns={
        "person_id": "patid",
        "INDEX_DATE": "index_date",
        "scre_result": "scre",
        "sbp_result": "sbp",
        "bmi_value": "bmi",
        "tc_value": "tc",
        "hdlc_value": "hdlc",
        "sex_at_birth": "sex",
    }
)

# save
final_result.to_csv("cleaned_data", index=False)